name: STM32 Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      uses: xanderhendriks/action-build-stm32cubeide@v5.0
      with:
        project-path: 'stm32ci_test'
        project-target: 'stm32ci_test'
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: |
          stm32ci_test/Release/stm32ci_test.*
