name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck

    - name: Build STM32CubeIde project
      # You may pin to the exact commit or the version.
      # uses: xanderhendriks/action-build-stm32cubeide@32d524575d85f129bf6ddd810622160577416bf3
      uses: xanderhendriks/action-build-stm32cubeide@v7.2
      with:
        # Path to STM32CubeIde project
        project-path: \
        # Which target in the STM32CubeIde project to build
        project-target: \
